[build]
builder = "RAILPACK"
watchPatterns = ["cmd/**", "internal/**", "go.mod", "go.sum"]

[deploy]
startCommand = "./out"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
