[build]
builder = "dockerfile"
dockerfilePath = "go/Dockerfile"
dockerContext = "go"
watchPatterns = ["go/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
